version: '3'

services:
  website:
    image: wissamrh/wissamrh:latest
    ports:
      - "80:80"
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    ports:
      - "3306:3306"
