name: Build, Push, and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set version as an environment variable
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Build App Docker image
      run: docker build -t wissamrh/wissamrh:${{ env.VERSION }} .

    - name: Build Database Docker image
      run: docker build -t wissamrh/mysql:${{ env.VERSION }} -f Dockerfile.database .

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push App Docker image
      run: docker push wissamrh/wissamrh:${{ env.VERSION }}

    - name: Push Database Docker image
      run: docker push wissamrh/mysql:${{ env.VERSION }}

    - name: Update ConfigMap Locally
      run: |
        sed -i "s/app_version: .*/app_version: \"${VERSION}\"/" configmap.yaml
