name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Website Docker Image
      run: |
        docker build -t  wissamrh/wissamrh:latest ./website
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push wissamrh/wissamrh:latest

    - name: Build and Push Database Docker Image
      run: |
        docker build -t wissamrh/wissamdatabase:latest ./database
        docker push wissamrh/wissamdatabase:latest

    - name: Deploy Containers
      run: docker-compose up -d
