name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set COMMIT_HASH variable
      run: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV  

    - name: Build App Docker image
      run: docker build -t wissamrh/wissamrh:latest .

    - name: Build Database Docker image
      run: docker build -t wissamrh/mysql:latest -f Dockerfile.database .

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push App Docker image
      run: docker push wissamrh/wissamrh:latest

    - name: Push Database Docker image
      run: docker push wissamrh/mysql:latest
