name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          wissamrh/wissamrh:latest
          wissamrh/mysql-web-app:latest

    - name: Deploy with Docker Compose
      run: docker-compose up -d
